
[common]
	#Acceleration Oil increment value.
	#Range: 0.001 ~ 1000.0
	accelerationIncrement = 1.0
	#Agility Oil increment value.
	#Range: 0.001 ~ 1000.0
	agilityIncrement = 0.2
	#Lightness Oil increment value.
	#Range: 0.001 ~ 1000.0
	lightnessIncrement = 0.5
	#Protection Oil increment value.
	#Range: 0.001 ~ 1000.0
	protectionIncrement = 3.0
	#Power Oil increment value.
	#Range: 0.001 ~ 1000.0
	powerIncrement = 5.0
	#Tenacity Oil increment value.
	#Range: 0.001 ~ 1000.0
	tenacityIncrement = 2.0

