
[general]
	#A very subtle animation, makes a pig's snout move when it oinks.
	#It only moves up and down ever so slightly, but it's there. Just a little bit more life for your livestock.
	"Oinky Pig" = true
	#A truly stunning visual addition. Spiders now finally have the knees they've always dreamed of.
	"Spider Knees" = true
	#Gives a jellyfish-like effect to the swimming animation of squids.
	#Also makes their tentacles flow more while moving.
	"Squiggly Squid Tentacles" = true
	#A pleasing visual change; this makes the insides of slimes flow around like liquid.
	#They splish-splosh about even more when they jump. The eyes, the mouth, and the core itself all move independently.
	"Jiggly Liquidy Slime" = true
	#This makes the udders on cows wobble around when they walk.
	#Also makes their udders have nipples.
	"Wobbly Cow Udder" = true
	#This one is pretty kneat. It makes sheep actually bend down to eat grass.
	#It's no longer just their head lowering, their whole body lowers down to get a sweet sample of that succulent cellulose.
	#Did you notice their KNEES bend too when they kneel?
	"Kneeling Sheep" = true
	#Takes away the stick tails of the current cats and gives them something nicer instead.
	#Fully animated flowing tails that move while they stand or run, and even curl around their bodies when they sit.
	"Curly Cat Tail" = true
	#This makes a snowman's arm swing when it throws a snowball.
	"Animated Snow Man Stick" = true
	#Divides ghast tentacles into parts and makes them wiggle realistically, like those tentacle monsters you always see at the movies.
	#Makes them a little more scary, but ultimately nicer to look at.
	"Wiggly Ghast Tentacles" = true
	#Takes away the stick tails of the current ocelots and gives them something nicer instead.
	#Fully animated flowing tails that move while they stand or run.
	"Flowy Ocelot Tail" = true
	#This one makes chicken beaks open and close when they cluck.
	#When they strut their heads move back and forth, the red thing under their beak swings around and their wings flap a little. Just like the real deal!
	"Bucka Chicken" = true
	#Adds a custom death animation to magma cubes, which causes their bodies to form into a pile of steamy, delicious hamburger patties when they die.
	#Unfortunately, you can't eat them because they're way too hot.
	"Magma Cube Burger" = true
	#A subtle change; this makes iron golems wiggle their big noses whenever they're hurt.
	#Exactly the same animation as for villagers, except for iron golems!
	"Wiggly Iron Golem Nose" = true
	#A subtle change; this makes villagers wiggle their big noses whenever they make their iconic sound.
	#It's a small change, but who doesn't get a kick out of it?
	"Wiggly Villager Nose" = true

[oinky_pig]
	#Mob variants these model changes shouldn't be applied to.
	#Format for every entry is "<namespace>:<path>". Path may use asterisk as wildcard parameter. Tags are not supported.
	"Mob Blacklist" = []
	#Mob sounds to play a unique animation for.
	#Useful for adding support for modded mob variants which have different sounds from their vanilla counterparts.
	#Format for every entry is "<namespace>:<path>". Path may use asterisk as wildcard parameter. Tags are not supported.
	"Mob Sounds" = ["minecraft:entity.pig.ambient", "snowpig:entity.snow_pig.ambient"]

[spider_knees]
	#Mob variants these model changes shouldn't be applied to.
	#Format for every entry is "<namespace>:<path>". Path may use asterisk as wildcard parameter. Tags are not supported.
	"Mob Blacklist" = []

[squiggly_squid_tentacles]
	#Mob variants these model changes shouldn't be applied to.
	#Format for every entry is "<namespace>:<path>". Path may use asterisk as wildcard parameter. Tags are not supported.
	"Mob Blacklist" = []
	#Define the max length of the tentacles.
	#Range: 1 ~ 8
	"Max Length" = 8

[jiggly_liquidy_slime]
	#Mob variants these model changes shouldn't be applied to.
	#Format for every entry is "<namespace>:<path>". Path may use asterisk as wildcard parameter. Tags are not supported.
	"Mob Blacklist" = []
	#Animation swing of inner slime parts.
	#Range: 1 ~ 20
	Squishiness = 5

[wobbly_cow_udder]
	#Mob variants these model changes shouldn't be applied to.
	#Format for every entry is "<namespace>:<path>". Path may use asterisk as wildcard parameter. Tags are not supported.
	"Mob Blacklist" = []
	#Swing amount of the utter when the cow is walking.
	#Range: 1 ~ 20
	"Swing Amount" = 5
	#Don't render four nipples on every cow's utter.
	"Hide Nipples" = false

[kneeling_sheep]
	#Mob variants these model changes shouldn't be applied to.
	#Format for every entry is "<namespace>:<path>". Path may use asterisk as wildcard parameter. Tags are not supported.
	"Mob Blacklist" = []

[curly_cat_tail]
	#Mob variants these model changes shouldn't be applied to.
	#Format for every entry is "<namespace>:<path>". Path may use asterisk as wildcard parameter. Tags are not supported.
	"Mob Blacklist" = []
	#Define the max length of the tail.
	#Range: 1 ~ 15
	"Max Length" = 15
	#Swing amount of the tail.
	#Range: 1 ~ 20
	"Tail Swing" = 7

[animated_snow_man_stick]
	#Mob variants these model changes shouldn't be applied to.
	#Format for every entry is "<namespace>:<path>". Path may use asterisk as wildcard parameter. Tags are not supported.
	"Mob Blacklist" = []
	#Mob sounds to play a unique animation for.
	#Useful for adding support for modded mob variants which have different sounds from their vanilla counterparts.
	#Format for every entry is "<namespace>:<path>". Path may use asterisk as wildcard parameter. Tags are not supported.
	"Mob Sounds" = ["minecraft:entity.snow_golem.shoot"]

[wiggly_ghast_tentacles]
	#Mob variants these model changes shouldn't be applied to.
	#Format for every entry is "<namespace>:<path>". Path may use asterisk as wildcard parameter. Tags are not supported.
	"Mob Blacklist" = []
	#Define the max length of the tentacles.
	#Range: 2 ~ 14
	"Max Length" = 14
	#Animation swing of the tentacles.
	#Range: 1 ~ 20
	"Animation Swing" = 5

[flowy_ocelot_tail]
	#Mob variants these model changes shouldn't be applied to.
	#Format for every entry is "<namespace>:<path>". Path may use asterisk as wildcard parameter. Tags are not supported.
	"Mob Blacklist" = []
	#Define the max length of the tail.
	#Range: 1 ~ 15
	"Max Length" = 15
	#Swing amount of the tail.
	#Range: 1 ~ 20
	"Tail Swing" = 7

[bucka_chicken]
	#Mob variants these model changes shouldn't be applied to.
	#Format for every entry is "<namespace>:<path>". Path may use asterisk as wildcard parameter. Tags are not supported.
	"Mob Blacklist" = []
	#Mob sounds to play a unique animation for.
	#Useful for adding support for modded mob variants which have different sounds from their vanilla counterparts.
	#Format for every entry is "<namespace>:<path>". Path may use asterisk as wildcard parameter. Tags are not supported.
	"Mob Sounds" = ["minecraft:entity.chicken.ambient"]
	#Move head back and forth when the entity is walking.
	"Move Head" = true
	#Wiggle chin when the entity is walking.
	"Wiggle Chin" = true
	#Flap wings when the entity is walking.
	"Flap Wings" = true
	#Animation swing for the head movement.
	#Range: 1 ~ 20
	"Head Swing" = 4
	#Animation swing for the chin movement.
	#Range: 1 ~ 20
	"Chin Swing" = 5
	#Animation swing of the wing flapping.
	#Range: 1 ~ 20
	"Wing Swing" = 3

[magma_cube_burger]
	#Mob variants these model changes shouldn't be applied to.
	#Format for every entry is "<namespace>:<path>". Path may use asterisk as wildcard parameter. Tags are not supported.
	"Mob Blacklist" = []

[sound_detection]
	#Block range for sound detection system to look for a mob that made a certain sound on the server, so the client may play an animation.
	#Range: 0.5 ~ 8.0
	"Sound Detection Range" = 1.5

[wiggly_iron_golem_nose]
	#Mob variants these model changes shouldn't be applied to.
	#Format for every entry is "<namespace>:<path>". Path may use asterisk as wildcard parameter. Tags are not supported.
	"Mob Blacklist" = []

[wiggly_villager_nose]
	#Mob variants these model changes shouldn't be applied to.
	#Format for every entry is "<namespace>:<path>". Path may use asterisk as wildcard parameter. Tags are not supported.
	"Mob Blacklist" = []
	#Mob sounds to play a unique animation for.
	#Useful for adding support for modded mob variants which have different sounds from their vanilla counterparts.
	#Format for every entry is "<namespace>:<path>". Path may use asterisk as wildcard parameter. Tags are not supported.
	"Mob Sounds" = ["minecraft:entity.villager.ambient", "minecraft:entity.villager.trade", "minecraft:entity.wandering_trader.ambient", "minecraft:entity.wandering_trader.trade"]

