
#Default strength muliplier of each rarity.
["Default Rarity Multipliers"]
	#If all items should recive random modifiers. Else they must be randomized through nbt.
	modify_all = true

	#Registry names of items that the modifier should also be applied to.
	["Default Rarity Multipliers"."Item Additions"]
		additions_lifesteal = []
		additions_fire = []
		additions_guarding = ["#crafttweaker:relics", "#blue_skies:arcs"]
		additions_frost = []
		additions_mending = []
		additions_learning = ["#crafttweaker:relics", "#blue_skies:arcs"]
		additions_reaching = ["#crafttweaker:relics", "#blue_skies:arcs"]
		additions_speed = []
		additions_swiftness = ["#crafttweaker:relics", "#blue_skies:arcs"]

["Modifier Weights"]

	#Chance of the suffix being chose out of others.
	["Modifier Weights"."Suffix Weights"]
		#Range: > 0
		weight_speed = 5
		#Range: > 0
		weight_learning = 0.1
		#Range: > 0
		weight_swiftness = 1
		#Range: > 0
		weight_guarding = 5

	#Chance of the prefix being chose out of others.
	["Modifier Weights"."Prefix Weights"]
		#Range: > 0
		weight_fire = 5
		#Range: > 0
		weight_reaching = 1
		#Range: > 0
		weight_lifesteal = 1
		#Range: > 0
		weight_mending = 0.5
		#Range: > 0
		weight_frost = 5

