
[ingame]
	#Range: 0.0 ~ 1.0
	laser_pointer_color = 0.328125
	show_health_indicator = false
	#Range: 1 ~ 10
	long_press_count = 2
	enable_laser_pointer = true
	camera_auto_switch = false
	filter_animation = true
	show_target_indicator = false

