
[custom_entity]

	[custom_entity.sample]
		type_name = "modid:type_name"
		impact = 0.5
		max_strikes = 1
		armor_negation = 0.0
		#Allowed Values: ZOMBIE, SKELETON, CREEPER, SPIDER, VINDICATOR
		ai_type = "ZOMBIE"
		texture_location = "modid:texture_location"

[custom_weaponry]

	[custom_weaponry.boneclub]
		armor_ignorance = 0.0
		hit_at_once = 2
		impact = 2.0
		#Allowed Values: AXE, FIST, HOE, PICKAXE, SHOVEL, SWORD, SPEAR, GREATSWORD, KATANA, TACHI, KNUCKLE, LONGSWORD, DAGGER, BOW, CROSSBOW
		weapon_type = "GREATSWORD"
		registry_name = "dungeons_gear:boneclub"

	[custom_weaponry.moon_daggers]
		armor_ignorance = 0.75
		hit_at_once = 2
		impact = 0.15
		#Allowed Values: AXE, FIST, HOE, PICKAXE, SHOVEL, SWORD, SPEAR, GREATSWORD, KATANA, TACHI, KNUCKLE, LONGSWORD, DAGGER, BOW, CROSSBOW
		weapon_type = "DAGGER"
		registry_name = "dungeons_gear:moon_dagger"

	[custom_weaponry.fortune_spear]
		armor_ignorance = 0.6
		hit_at_once = 2
		impact = 0.3
		#Allowed Values: AXE, FIST, HOE, PICKAXE, SHOVEL, SWORD, SPEAR, GREATSWORD, KATANA, TACHI, KNUCKLE, LONGSWORD, DAGGER, BOW, CROSSBOW
		weapon_type = "SPEAR"
		registry_name = "dungeons_gear:whispering_spear"

	[custom_weaponry.grave_bane]
		armor_ignorance = 0.9
		hit_at_once = 2
		impact = 0.1
		#Allowed Values: AXE, FIST, HOE, PICKAXE, SHOVEL, SWORD, SPEAR, GREATSWORD, KATANA, TACHI, KNUCKLE, LONGSWORD, DAGGER, BOW, CROSSBOW
		weapon_type = "SPEAR"
		registry_name = "dungeons_gear:grave_bane"

	[custom_weaponry.great_hammer]
		armor_ignorance = 0.0
		hit_at_once = 2
		impact = 0.5
		#Allowed Values: AXE, FIST, HOE, PICKAXE, SHOVEL, SWORD, SPEAR, GREATSWORD, KATANA, TACHI, KNUCKLE, LONGSWORD, DAGGER, BOW, CROSSBOW
		weapon_type = "AXE"
		registry_name = "dungeons_gear:great_hammer"

	[custom_weaponry.unmaykr]
		armor_ignorance = 0.0
		hit_at_once = 1
		impact = 0.5
		#Allowed Values: AXE, FIST, HOE, PICKAXE, SHOVEL, SWORD, SPEAR, GREATSWORD, KATANA, TACHI, KNUCKLE, LONGSWORD, DAGGER, BOW, CROSSBOW
		weapon_type = "CROSSBOW"
		registry_name = "doom:unmaykr"

	[custom_weaponry.great_axeblade]
		armor_ignorance = 0.9
		hit_at_once = 5
		impact = 0.5
		#Allowed Values: AXE, FIST, HOE, PICKAXE, SHOVEL, SWORD, SPEAR, GREATSWORD, KATANA, TACHI, KNUCKLE, LONGSWORD, DAGGER, BOW, CROSSBOW
		weapon_type = "GREATSWORD"
		registry_name = "dungeons_gear:great_axeblade"

	[custom_weaponry.frost_slayer]
		armor_ignorance = 0.7
		hit_at_once = 5
		impact = 0.3
		#Allowed Values: AXE, FIST, HOE, PICKAXE, SHOVEL, SWORD, SPEAR, GREATSWORD, KATANA, TACHI, KNUCKLE, LONGSWORD, DAGGER, BOW, CROSSBOW
		weapon_type = "GREATSWORD"
		registry_name = "dungeons_gear:frost_slayer"

	[custom_weaponry.mauler]
		armor_ignorance = 0.75
		hit_at_once = 1
		impact = 0.3
		#Allowed Values: AXE, FIST, HOE, PICKAXE, SHOVEL, SWORD, SPEAR, GREATSWORD, KATANA, TACHI, KNUCKLE, LONGSWORD, DAGGER, BOW, CROSSBOW
		weapon_type = "FIST"
		registry_name = "dungeons_gear:mauler"

	[custom_weaponry.katana]
		armor_ignorance = 0.7
		hit_at_once = 2
		impact = 0.1
		#Allowed Values: AXE, FIST, HOE, PICKAXE, SHOVEL, SWORD, SPEAR, GREATSWORD, KATANA, TACHI, KNUCKLE, LONGSWORD, DAGGER, BOW, CROSSBOW
		weapon_type = "KATANA"
		registry_name = "dungeons_gear:katana"

	[custom_weaponry.bone_cudgel]
		armor_ignorance = 0.0
		hit_at_once = 2
		impact = 2.0
		#Allowed Values: AXE, FIST, HOE, PICKAXE, SHOVEL, SWORD, SPEAR, GREATSWORD, KATANA, TACHI, KNUCKLE, LONGSWORD, DAGGER, BOW, CROSSBOW
		weapon_type = "GREATSWORD"
		registry_name = "dungeons_gear:bone_cudgel"

	[custom_weaponry.encrusted_anchor]
		armor_ignorance = 0.5
		hit_at_once = 2
		impact = 2.0
		#Allowed Values: AXE, FIST, HOE, PICKAXE, SHOVEL, SWORD, SPEAR, GREATSWORD, KATANA, TACHI, KNUCKLE, LONGSWORD, DAGGER, BOW, CROSSBOW
		weapon_type = "GREATSWORD"
		registry_name = "dungeons_gear:encrusted_anchor"

	[custom_weaponry.broadsword]
		armor_ignorance = 0.6
		hit_at_once = 5
		impact = 0.5
		#Allowed Values: AXE, FIST, HOE, PICKAXE, SHOVEL, SWORD, SPEAR, GREATSWORD, KATANA, TACHI, KNUCKLE, LONGSWORD, DAGGER, BOW, CROSSBOW
		weapon_type = "GREATSWORD"
		registry_name = "dungeons_gear:broadsword"

	[custom_weaponry.claymore]
		armor_ignorance = 0.6
		hit_at_once = 5
		impact = 0.3
		#Allowed Values: AXE, FIST, HOE, PICKAXE, SHOVEL, SWORD, SPEAR, GREATSWORD, KATANA, TACHI, KNUCKLE, LONGSWORD, DAGGER, BOW, CROSSBOW
		weapon_type = "GREATSWORD"
		registry_name = "dungeons_gear:claymore"

	[custom_weaponry.sickles]
		armor_ignorance = 0.6
		hit_at_once = 2
		impact = 0.1
		#Allowed Values: AXE, FIST, HOE, PICKAXE, SHOVEL, SWORD, SPEAR, GREATSWORD, KATANA, TACHI, KNUCKLE, LONGSWORD, DAGGER, BOW, CROSSBOW
		weapon_type = "DAGGER"
		registry_name = "dungeons_gear:sickle"

	[custom_weaponry.chill_gale_knife]
		armor_ignorance = 1.0
		hit_at_once = 2
		impact = 0.0
		#Allowed Values: AXE, FIST, HOE, PICKAXE, SHOVEL, SWORD, SPEAR, GREATSWORD, KATANA, TACHI, KNUCKLE, LONGSWORD, DAGGER, BOW, CROSSBOW
		weapon_type = "DAGGER"
		registry_name = "dungeons_gear:chill_gale_knife"

	[custom_weaponry.growing_staff]
		armor_ignorance = 0.7
		hit_at_once = 3
		impact = 0.5
		#Allowed Values: AXE, FIST, HOE, PICKAXE, SHOVEL, SWORD, SPEAR, GREATSWORD, KATANA, TACHI, KNUCKLE, LONGSWORD, DAGGER, BOW, CROSSBOW
		weapon_type = "SPEAR"
		registry_name = "dungeons_gear:growing_staff"

	[custom_weaponry.shotgun]
		armor_ignorance = 0.5
		hit_at_once = 1
		impact = 0.5
		#Allowed Values: AXE, FIST, HOE, PICKAXE, SHOVEL, SWORD, SPEAR, GREATSWORD, KATANA, TACHI, KNUCKLE, LONGSWORD, DAGGER, BOW, CROSSBOW
		weapon_type = "CROSSBOW"
		registry_name = "doom:shotgun"

	[custom_weaponry.soul_knife]
		armor_ignorance = 1.0
		hit_at_once = 2
		impact = 0.0
		#Allowed Values: AXE, FIST, HOE, PICKAXE, SHOVEL, SWORD, SPEAR, GREATSWORD, KATANA, TACHI, KNUCKLE, LONGSWORD, DAGGER, BOW, CROSSBOW
		weapon_type = "DAGGER"
		registry_name = "dungeons_gear:soul_knife"

	[custom_weaponry.chaingun]
		armor_ignorance = 0.5
		hit_at_once = 1
		impact = 0.5
		#Allowed Values: AXE, FIST, HOE, PICKAXE, SHOVEL, SWORD, SPEAR, GREATSWORD, KATANA, TACHI, KNUCKLE, LONGSWORD, DAGGER, BOW, CROSSBOW
		weapon_type = "CROSSBOW"
		registry_name = "doom:chaingun"

	[custom_weaponry.mace]
		armor_ignorance = 0.3
		hit_at_once = 2
		impact = 0.7
		#Allowed Values: AXE, FIST, HOE, PICKAXE, SHOVEL, SWORD, SPEAR, GREATSWORD, KATANA, TACHI, KNUCKLE, LONGSWORD, DAGGER, BOW, CROSSBOW
		weapon_type = "AXE"
		registry_name = "dungeons_gear:mace"

	[custom_weaponry.ballista]
		armor_ignorance = 0.0
		hit_at_once = 1
		impact = 0.5
		#Allowed Values: AXE, FIST, HOE, PICKAXE, SHOVEL, SWORD, SPEAR, GREATSWORD, KATANA, TACHI, KNUCKLE, LONGSWORD, DAGGER, BOW, CROSSBOW
		weapon_type = "CROSSBOW"
		registry_name = "doom:ballista"

	[custom_weaponry.fighters_bindings]
		armor_ignorance = 0.3
		hit_at_once = 1
		impact = 0.6
		#Allowed Values: AXE, FIST, HOE, PICKAXE, SHOVEL, SWORD, SPEAR, GREATSWORD, KATANA, TACHI, KNUCKLE, LONGSWORD, DAGGER, BOW, CROSSBOW
		weapon_type = "FIST"
		registry_name = "dungeons_gear:fighters_bindings"

	[custom_weaponry.mechanized_sawblade]
		armor_ignorance = 1.0
		hit_at_once = 2
		impact = 0.0
		#Allowed Values: AXE, FIST, HOE, PICKAXE, SHOVEL, SWORD, SPEAR, GREATSWORD, KATANA, TACHI, KNUCKLE, LONGSWORD, DAGGER, BOW, CROSSBOW
		weapon_type = "TACHI"
		registry_name = "dungeons_gear:mechanized_sawblade"

	[custom_weaponry.dark_katana]
		armor_ignorance = 0.7
		hit_at_once = 2
		impact = 0.1
		#Allowed Values: AXE, FIST, HOE, PICKAXE, SHOVEL, SWORD, SPEAR, GREATSWORD, KATANA, TACHI, KNUCKLE, LONGSWORD, DAGGER, BOW, CROSSBOW
		weapon_type = "KATANA"
		registry_name = "dungeons_gear:dark_katana"

	[custom_weaponry.hammer_of_gravity]
		armor_ignorance = 0.0
		hit_at_once = 2
		impact = 0.5
		#Allowed Values: AXE, FIST, HOE, PICKAXE, SHOVEL, SWORD, SPEAR, GREATSWORD, KATANA, TACHI, KNUCKLE, LONGSWORD, DAGGER, BOW, CROSSBOW
		weapon_type = "AXE"
		registry_name = "dungeons_gear:hammer_of_gravity"

	[custom_weaponry.eternal_knife]
		armor_ignorance = 1.0
		hit_at_once = 2
		impact = 0.0
		#Allowed Values: AXE, FIST, HOE, PICKAXE, SHOVEL, SWORD, SPEAR, GREATSWORD, KATANA, TACHI, KNUCKLE, LONGSWORD, DAGGER, BOW, CROSSBOW
		weapon_type = "DAGGER"
		registry_name = "dungeons_gear:eternal_knife"

	[custom_weaponry.suns_grace]
		armor_ignorance = 0.3
		hit_at_once = 2
		impact = 0.5
		#Allowed Values: AXE, FIST, HOE, PICKAXE, SHOVEL, SWORD, SPEAR, GREATSWORD, KATANA, TACHI, KNUCKLE, LONGSWORD, DAGGER, BOW, CROSSBOW
		weapon_type = "AXE"
		registry_name = "dungeons_gear:suns_grace"

	[custom_weaponry.fangs_of_frost]
		armor_ignorance = 0.7
		hit_at_once = 2
		impact = 0.2
		#Allowed Values: AXE, FIST, HOE, PICKAXE, SHOVEL, SWORD, SPEAR, GREATSWORD, KATANA, TACHI, KNUCKLE, LONGSWORD, DAGGER, BOW, CROSSBOW
		weapon_type = "DAGGER"
		registry_name = "dungeons_gear:fang_of_frost"

	[custom_weaponry.spear]
		armor_ignorance = 0.6
		hit_at_once = 2
		impact = 0.3
		#Allowed Values: AXE, FIST, HOE, PICKAXE, SHOVEL, SWORD, SPEAR, GREATSWORD, KATANA, TACHI, KNUCKLE, LONGSWORD, DAGGER, BOW, CROSSBOW
		weapon_type = "SPEAR"
		registry_name = "dungeons_gear:spear"

	[custom_weaponry.stormlander]
		armor_ignorance = 0.2
		hit_at_once = 2
		impact = 0.5
		#Allowed Values: AXE, FIST, HOE, PICKAXE, SHOVEL, SWORD, SPEAR, GREATSWORD, KATANA, TACHI, KNUCKLE, LONGSWORD, DAGGER, BOW, CROSSBOW
		weapon_type = "AXE"
		registry_name = "dungeons_gear:stormlander"

	[custom_weaponry.nightmares_bite]
		armor_ignorance = 0.8
		hit_at_once = 2
		impact = 0.4
		#Allowed Values: AXE, FIST, HOE, PICKAXE, SHOVEL, SWORD, SPEAR, GREATSWORD, KATANA, TACHI, KNUCKLE, LONGSWORD, DAGGER, BOW, CROSSBOW
		weapon_type = "DAGGER"
		registry_name = "dungeons_gear:nightmares_bite"

	[custom_weaponry.masters_katana]
		armor_ignorance = 1.0
		hit_at_once = 2
		impact = 0.0
		#Allowed Values: AXE, FIST, HOE, PICKAXE, SHOVEL, SWORD, SPEAR, GREATSWORD, KATANA, TACHI, KNUCKLE, LONGSWORD, DAGGER, BOW, CROSSBOW
		weapon_type = "KATANA"
		registry_name = "dungeons_gear:masters_katana"

	[custom_weaponry.shear_dagger]
		armor_ignorance = 0.8
		hit_at_once = 2
		impact = 0.1
		#Allowed Values: AXE, FIST, HOE, PICKAXE, SHOVEL, SWORD, SPEAR, GREATSWORD, KATANA, TACHI, KNUCKLE, LONGSWORD, DAGGER, BOW, CROSSBOW
		weapon_type = "DAGGER"
		registry_name = "dungeons_gear:shear_dagger"

	[custom_weaponry.battlestaff]
		armor_ignorance = 0.2
		hit_at_once = 3
		impact = 0.8
		#Allowed Values: AXE, FIST, HOE, PICKAXE, SHOVEL, SWORD, SPEAR, GREATSWORD, KATANA, TACHI, KNUCKLE, LONGSWORD, DAGGER, BOW, CROSSBOW
		weapon_type = "SPEAR"
		registry_name = "dungeons_gear:battlestaff"

	[custom_weaponry.gauntlet]
		armor_ignorance = 0.0
		hit_at_once = 1
		impact = 0.2
		#Allowed Values: AXE, FIST, HOE, PICKAXE, SHOVEL, SWORD, SPEAR, GREATSWORD, KATANA, TACHI, KNUCKLE, LONGSWORD, DAGGER, BOW, CROSSBOW
		weapon_type = "FIST"
		registry_name = "dungeons_gear:gauntlet"

	[custom_weaponry.supershotgun]
		armor_ignorance = 1.0
		hit_at_once = 1
		impact = 1.0
		#Allowed Values: AXE, FIST, HOE, PICKAXE, SHOVEL, SWORD, SPEAR, GREATSWORD, KATANA, TACHI, KNUCKLE, LONGSWORD, DAGGER, BOW, CROSSBOW
		weapon_type = "CROSSBOW"
		registry_name = "doom:supershotgun"

	[custom_weaponry.glaive]
		armor_ignorance = 0.9
		hit_at_once = 2
		impact = 0.1
		#Allowed Values: AXE, FIST, HOE, PICKAXE, SHOVEL, SWORD, SPEAR, GREATSWORD, KATANA, TACHI, KNUCKLE, LONGSWORD, DAGGER, BOW, CROSSBOW
		weapon_type = "SPEAR"
		registry_name = "dungeons_gear:glaive"

	[custom_weaponry.heartstealer]
		armor_ignorance = 0.6
		hit_at_once = 3
		impact = 0.3
		#Allowed Values: AXE, FIST, HOE, PICKAXE, SHOVEL, SWORD, SPEAR, GREATSWORD, KATANA, TACHI, KNUCKLE, LONGSWORD, DAGGER, BOW, CROSSBOW
		weapon_type = "LONGSWORD"
		registry_name = "dungeons_gear:heartstealer"

	[custom_weaponry.resolute_tempest_knife]
		armor_ignorance = 1.0
		hit_at_once = 2
		impact = 0.0
		#Allowed Values: AXE, FIST, HOE, PICKAXE, SHOVEL, SWORD, SPEAR, GREATSWORD, KATANA, TACHI, KNUCKLE, LONGSWORD, DAGGER, BOW, CROSSBOW
		weapon_type = "DAGGER"
		registry_name = "dungeons_gear:resolute_tempest_knife"

	[custom_weaponry.heavycannon]
		armor_ignorance = 0.5
		hit_at_once = 1
		impact = 0.5
		#Allowed Values: AXE, FIST, HOE, PICKAXE, SHOVEL, SWORD, SPEAR, GREATSWORD, KATANA, TACHI, KNUCKLE, LONGSWORD, DAGGER, BOW, CROSSBOW
		weapon_type = "CROSSBOW"
		registry_name = "doom:heavycannon"

	[custom_weaponry.battlestaff_of_terror]
		armor_ignorance = 0.3
		hit_at_once = 3
		impact = 0.5
		#Allowed Values: AXE, FIST, HOE, PICKAXE, SHOVEL, SWORD, SPEAR, GREATSWORD, KATANA, TACHI, KNUCKLE, LONGSWORD, DAGGER, BOW, CROSSBOW
		weapon_type = "SPEAR"
		registry_name = "dungeons_gear:battlestaff_of_terror"

	[custom_weaponry.pistol]
		armor_ignorance = 0.5
		hit_at_once = 1
		impact = 0.5
		#Allowed Values: AXE, FIST, HOE, PICKAXE, SHOVEL, SWORD, SPEAR, GREATSWORD, KATANA, TACHI, KNUCKLE, LONGSWORD, DAGGER, BOW, CROSSBOW
		weapon_type = "CROSSBOW"
		registry_name = "doom:pistol"

	[custom_weaponry.sample]
		armor_ignorance = 0.0
		hit_at_once = 1
		impact = 0.5
		#Allowed Values: AXE, FIST, HOE, PICKAXE, SHOVEL, SWORD, SPEAR, GREATSWORD, KATANA, TACHI, KNUCKLE, LONGSWORD, DAGGER, BOW, CROSSBOW
		weapon_type = "SWORD"
		registry_name = "epicfight:registryname"

	[custom_weaponry.flail]
		armor_ignorance = 0.3
		hit_at_once = 2
		impact = 0.7
		#Allowed Values: AXE, FIST, HOE, PICKAXE, SHOVEL, SWORD, SPEAR, GREATSWORD, KATANA, TACHI, KNUCKLE, LONGSWORD, DAGGER, BOW, CROSSBOW
		weapon_type = "AXE"
		registry_name = "dungeons_gear:flail"

	[custom_weaponry.venom_glaive]
		armor_ignorance = 0.9
		hit_at_once = 2
		impact = 0.1
		#Allowed Values: AXE, FIST, HOE, PICKAXE, SHOVEL, SWORD, SPEAR, GREATSWORD, KATANA, TACHI, KNUCKLE, LONGSWORD, DAGGER, BOW, CROSSBOW
		weapon_type = "SPEAR"
		registry_name = "dungeons_gear:venom_glaive"

	[custom_weaponry.broken_sawblade]
		armor_ignorance = 0.65
		hit_at_once = 2
		impact = 0.0
		#Allowed Values: AXE, FIST, HOE, PICKAXE, SHOVEL, SWORD, SPEAR, GREATSWORD, KATANA, TACHI, KNUCKLE, LONGSWORD, DAGGER, BOW, CROSSBOW
		weapon_type = "TACHI"
		registry_name = "dungeons_gear:broken_sawblade"

	[custom_weaponry.anchor]
		armor_ignorance = 0.5
		hit_at_once = 2
		impact = 2.0
		#Allowed Values: AXE, FIST, HOE, PICKAXE, SHOVEL, SWORD, SPEAR, GREATSWORD, KATANA, TACHI, KNUCKLE, LONGSWORD, DAGGER, BOW, CROSSBOW
		weapon_type = "GREATSWORD"
		registry_name = "dungeons_gear:anchor"

	[custom_weaponry.daggers]
		armor_ignorance = 0.5
		hit_at_once = 2
		impact = 0.2
		#Allowed Values: AXE, FIST, HOE, PICKAXE, SHOVEL, SWORD, SPEAR, GREATSWORD, KATANA, TACHI, KNUCKLE, LONGSWORD, DAGGER, BOW, CROSSBOW
		weapon_type = "DAGGER"
		registry_name = "dungeons_gear:dagger"

	[custom_weaponry.whispering_spear]
		armor_ignorance = 0.8
		hit_at_once = 2
		impact = 0.2
		#Allowed Values: AXE, FIST, HOE, PICKAXE, SHOVEL, SWORD, SPEAR, GREATSWORD, KATANA, TACHI, KNUCKLE, LONGSWORD, DAGGER, BOW, CROSSBOW
		weapon_type = "SPEAR"
		registry_name = "dungeons_gear:whispering_spear"

	[custom_weaponry.tempest_knife]
		armor_ignorance = 1.0
		hit_at_once = 2
		impact = 0.0
		#Allowed Values: AXE, FIST, HOE, PICKAXE, SHOVEL, SWORD, SPEAR, GREATSWORD, KATANA, TACHI, KNUCKLE, LONGSWORD, DAGGER, BOW, CROSSBOW
		weapon_type = "DAGGER"
		registry_name = "dungeons_gear:tempest_knife"

	[custom_weaponry.soul_fist]
		armor_ignorance = 0.5
		hit_at_once = 1
		impact = 0.5
		#Allowed Values: AXE, FIST, HOE, PICKAXE, SHOVEL, SWORD, SPEAR, GREATSWORD, KATANA, TACHI, KNUCKLE, LONGSWORD, DAGGER, BOW, CROSSBOW
		weapon_type = "FIST"
		registry_name = "dungeons_gear:soul_fist"

[custom_armor]

	[custom_armor.sample]
		stun_armor = 0.0
		weight = 0.0
		registry_name = "epicfight:registryname"

