
#Beam Config
["Loot Beams"]
	#The radius of the Loot Beam.
	#Range: 0.0 ~ 5.0
	beam_radius = 0.35
	#Transparency of the Loot Beam.
	#Range: 0.0 ~ 1.0
	beam_alpha = 0.85
	#If beams should be colored the same as the Items name (excludes name colors from rarity). This has priority over render_rarity_color.
	render_name_color = true
	#If beams should be colored the same as the Items rarity.
	render_rarity_color = true
	#The height of the Loot Beam.
	#Range: 0.0 ~ 10.0
	beam_height = 1.6
	#Overrides an item's beam color with hex color. Must follow the specific format: (registryname=hexcolor) Or (#tagname=hexcolor). Example: "minecraft:stone=0xFFFFFF".
	color_overrides = ["#crafttweaker:exotics=0x03FFA7", "#crafttweaker:trophies=0xB580FF", "#crafttweaker:ancient=0xFF0037", "#crafttweaker:anointment=0xE7F06E", "#crafttweaker:uncommon=0x55FF55", "#crafttweaker:rare=0x5555FF", "#crafttweaker:healing=0xFF0000", "#crafttweaker:currency=0xA7C4F2"]
	#The Y-offset of the loot beam.
	#Range: -30.0 ~ 30.0
	beam_y_offset = 0.0

	#Item nametags
	["Loot Beams".Nametags]
		#Scale of the nametag.
		#Range: -10.0 ~ 10.0
		nametag_scale = 1.0
		#If Item nametags should be rendered.
		render_nametags = true
		#If Item nametags should be rendered when looking at items.
		render_nametags_onlook = true
		#How close the player has to look at the item to render the nametag.
		#Range: 0.0 ~ 5.0
		nametag_look_sensitivity = 0.05
		#Transparency of the nametag background/border.
		#Range: 0.0 ~ 1.0
		nametag_background_alpha = 0.25
		#Render nametags as bordered. Set to false for flat nametag with background.
		borders = true
		#The Y-offset of the nametag.
		#Range: -30.0 ~ 30.0
		nametag_y_offset = 0.75
		#Define what the smaller tag should render on. Example: "Exotic", "Ancient". The string supplied has to be the tooltip line below the name. This is really only used for modpacks.
		custom_rarities = ["Exotic", "Ancient", "Relic", "Trophy", "Anointment", "Common", "Currency"]
		#If a smaller tag should be rendered under with DMCLoot rarities.
		dmcloot_compat_rarity = true
		#Transparency of the nametag text.
		#Range: 0.0 ~ 1.0
		nametag_text_alpha = 1.0
		#If the count of item's should also be shown in the nametag.
		render_stackcount = true

	#Item Config
	["Loot Beams".Items]
		#If Loot Beams should only be rendered on equipment. (Equipment includes: Swords, Tools, Armor, Shields, Bows, Crossbows, Tridents, Arrows, and Fishing Rods)
		only_equipment = false
		#Registry names of items that Loot Beams should NOT render on. This has priority over everything.
		blacklist = []
		#If all Items Loot Beams should be rendered. Has priority over only_equipment.
		all_items = true
		#Registry names of items that Loot Beams should render on. Example: "minecraft:stone", "minecraft:iron_ingot"
		whitelist = []

