
[general]
	clientID = 871246375919181834
	enabled = true
	debugging = false
	configScreen = true
	launcherIntegration = false
	updater = false
	version = 9

[init]
	enabled = true
	description = "Damned Minecraft is loading"
	state = "Game Starting..."
	largeImageKey = "dmc_logo"
	largeImageText = "It's Minecraft %mcver%, but Damned!"
	smallImageKey = "dmc_logo"
	smallImageText = "%mods% mods installed"
	buttons = []

[main_menu]
	enabled = true
	description = "%player% is currently lazy"
	state = "Trembling in fear on the main menu"
	largeImageKey = "dmc_logo"
	largeImageText = "It's Minecraft %mcver%, but Damned!"
	smallImageKey = "dmc_logo"
	smallImageText = "%mods% mods installed"
	buttons = []

[server_list]
	enabled = true
	description = "%player% is looking for a server"
	state = "Searching for friends"
	largeImageKey = "dmc_logo"
	largeImageText = "It's Minecraft %mcver%, but Damned!"
	smallImageKey = "dmc_logo"
	smallImageText = "%mods% mods installed"
	buttons = []

[join_game]
	enabled = true
	description = "%player% is joining a game"
	state = "Joining Game"
	largeImageKey = "dmc_logo"
	largeImageText = "It's Minecraft %mcver%, but Damned!"
	smallImageKey = "dmc_logo"
	smallImageText = "%mods% mods installed"
	buttons = []

[single_player]
	enabled = true
	description = "Currently In %world%"
	state = "Exploring the damned wilds"
	largeImageKey = "dmc_logo"
	largeImageText = "It's Minecraft %mcver%, but Damned!"
	smallImageKey = "dmc_logo"
	smallImageText = "%mods% mods installed"
	buttons = []

[multi_player]
	enabled = true
	description = "Playing on %servername% with %players% players"
	state = "Playing with their party"
	largeImageKey = "dmc_logo"
	largeImageText = "It's Minecraft %mcver%, but Damned!"
	smallImageKey = "dmc_logo"
	smallImageText = "%mods% mods installed"
	buttons = []

[generic]
	description = "Playing Damned Minecraft"
	state = ""
	largeImageKey = "dmc_logo"
	largeImageText = "It's Minecraft %mcver%, but Damned!"
	smallImageKey = "dmc_logo"
	smallImageText = "%mods% mods installed"
	buttons = []

[world_images]
	enabled = false

	[[world_images.worlds]]
		worldname = "overworld"
		largeImageKey = "overworld"
		largeImageText = "In the Overworld"
		smallImageKey = "dmc_logo"
		smallImageText = "%mods% mods installed"

	[[world_images.worlds]]
		worldname = "the_nether"
		largeImageKey = "nether"
		largeImageText = "In the Nether"
		smallImageKey = "dmc_logo"
		smallImageText = "%mods% mods installed"

	[[world_images.worlds]]
		worldname = "the_end"
		largeImageKey = "end"
		largeImageText = "In the End"
		smallImageKey = "dmc_logo"
		smallImageText = "%mods% mods installed"

